				<footer class="footer text-right">
					<span class="pull-left"><strong><?= SITE_NAME ?></strong> <small>v21.11.0 <small>beta</small></small></span>
					© <?= date('Y') ?> <?= SITE_NAME ?>
				</footer>
			</div>
		</div>
		<script type="text/javascript" src="<?=URL_ROOT?>/assets/plugins/jquery/jquery.min.js"></script>
		<script type="text/javascript" src="<?=URL_ROOT?>/assets/plugins/bootstrap/js/popper.min.js"></script>
		<script type="text/javascript" src="<?=URL_ROOT?>/assets/plugins/bootstrap/js/bootstrap.min.js"></script>
		<script type="text/javascript" src="<?=URL_ROOT?>/assets/js/jquery.slimscroll.js"></script>
		<script type="text/javascript" src="<?=URL_ROOT?>/assets/js/waves.js"></script>
		<script type="text/javascript" src="<?=URL_ROOT?>/assets/js/sidebarmenu.js"></script>
		<script type="text/javascript" src="<?=URL_ROOT?>/assets/plugins/sticky-kit-master/dist/sticky-kit.min.js"></script>
		<script type="text/javascript" src="<?=URL_ROOT?>/assets/plugins/moment/min/moment.min.js"></script>
		<script type="text/javascript" src="<?=URL_ROOT?>/assets/js/custom.js?2302271"></script>
		<script type="text/javascript" src="<?=URL_ROOT?>/assets/plugins/sparkline/jquery.sparkline.min.js"></script>
		<script type="text/javascript" src="<?=URL_ROOT?>/assets/plugins/blockUI/jquery.blockUI.js"></script>
		<script type="text/javascript" src="<?=URL_ROOT?>/assets/plugins/sweetalert/sweetalert.min.js"></script>
		<script type="text/javascript" src="<?=URL_ROOT?>/assets/plugins/typeahead.js-master/dist/typeahead.bundle.min.js"></script>
		<script type="text/javascript" src="<?=URL_ROOT?>/assets/plugins/inputmask/dist/min/jquery.inputmask.bundle.min.js"></script>
		<script type="text/javascript" src="<?=URL_ROOT?>/assets/js/mask.init.js"></script>
		<script type="text/javascript" src="<?=URL_ROOT?>/assets/plugins/datatables/jquery.dataTables.min.js"></script>
		<script type="text/javascript" src="<?=URL_ROOT?>/assets/plugins/datatables/dataTables.buttons.min.js"></script>
		<!-- <script type="text/javascript" src="<?=URL_ROOT?>/assets/plugins/datatables/buttons.print.min.js"></script>
		<script type="text/javascript" src="<?=URL_ROOT?>/assets/plugins/datatables/jszip.min.js"></script>
		<script type="text/javascript" src="<?=URL_ROOT?>/assets/plugins/datatables/pdfmake.min.js"></script>
		<script type="text/javascript" src="<?=URL_ROOT?>/assets/plugins/datatables/vfs_fonts.js"></script>
		<script type="text/javascript" src="<?=URL_ROOT?>/assets/plugins/datatables/buttons.html5.min.js"></script>
		<script type="text/javascript" src="<?=URL_ROOT?>/assets/plugins/jquery-asColorPicker-master/libs/jquery-asColor.js"></script>
		<script type="text/javascript" src="<?=URL_ROOT?>/assets/plugins/jquery-asColorPicker-master/dist/jquery-asColorPicker.min.js"></script>
		<script type="text/javascript" src="<?=URL_ROOT?>/assets/plugins/bootstrap-daterangepicker/daterangepicker.js"></script>
		<script type="text/javascript" src="<?=URL_ROOT?>/assets/plugins/bootstrap-datepicker/bootstrap-datepicker.min.js"></script>
		<script type="text/javascript" src="<?=URL_ROOT?>/assets/plugins/bootstrap-datepicker/bootstrap-datepicker.es.js"></script>
		<script type="text/javascript" src="<?=URL_ROOT?>/assets/plugins/Chart.js/Chart.min.js"></script>
		<script type="text/javascript" src="<?=URL_ROOT?>/assets/plugins/Chart.js/chartjs-plugin-datalabels.min.js"></script>
		<script type="text/javascript" src="<?=URL_ROOT?>/assets/plugins/lightbox/js/lightbox.js"></script>
		<script type="text/javascript" src="<?=URL_ROOT?>/assets/plugins/confirm/js/jquery-confirm.min.js"></script>
		<script type="text/javascript" src="<?=URL_ROOT?>/assets/plugins/summernote/dist/summernote.min.js"></script>
		<script type="text/javascript" src="<?=URL_ROOT?>/assets/plugins/jsBarcode/JsBarcode.all.min.js"></script>
		<script type="text/javascript" src="<?= URL_ROOT ?>/assets/plugins/summernote-emoji-master/js/config.js"></script>
		<script type="text/javascript" src="<?= URL_ROOT ?>/assets/plugins/summernote-emoji-master/js/tam-emoji.min.js"></script>
		<script type="text/javascript" src="<?=URL_ROOT?>/assets/plugins/jquery-asColorPicker-master/libs/jquery-asColor.js"></script>
		<script type="text/javascript" src="<?=URL_ROOT?>/assets/plugins/jquery-asColorPicker-master/dist/jquery-asColorPicker.min.js"></script>
		<script type="text/javascript" src="<?=URL_ROOT?>/assets/plugins/rateit/jquery.rateit.min.js"></script>
		<script type="text/javascript" src="<?=URL_ROOT?>/assets/plugins/md5/md5.min.js"></script>
		<script type="text/javascript" src="<?=URL_ROOT?>/assets/plugins/select2/dist/js/select2.min.js"></script> -->
		<script type="text/javascript" src="<?=URL_ROOT?>/assets/plugins/session-timeout/jquery.sessionTimeout.min.js"></script>
		<script type="text/javascript" src="<?=URL_ROOT?>/assets/plugins/bootstrap-select/bootstrap-select.min.js"></script>
		<script type="text/javascript" src="<?= URL_ROOT ?>/assets/plugins/dropify/dist/js/dropify.min.js"></script>
		<script src="<?=URL_ROOT?>/assets/plugins/toast/toastr.min.js"></script>

		<script>
			$(function(){

				// $(document).on('focusin', 'input, textarea', function() { $(this).select(); });
				// $(document).on('focus', 'input, textarea', function() { item = $(this); setTimeout(() => { item.select(); }, 100); });
				// $(document).on('mouseleave', '[data-toggle="tooltip"]', function() { $(document).find('.tooltip[role="tooltip"]').remove(); });

				/* < ?php if($_SESSION['usuario']->tipo==1 && !in_array(MOD_USUARIOS_NOBLOQUEO, $permisos)): ?>
				$.sessionTimeout({
					heading: 'h5',
					title: 'Sesión por expirar',
					message: 'Tu sesión está a punto de expirar. ¿Deseas seguir conectado?',
					countdownMessage: "Se cerrará en {timer} segundos.",
					warnAfter: 270000, 
					redirUrl: '< ?= URL_ROOT ?>/usuario/lock/'+encodeURIComponent(window.location.pathname+window.location.hash), 
					redirAfter: 300000, 
					keepAlive: true,
					keepAliveUrl: '< ?= URL_ROOT ?>/usuario/renovarToken/', 
					logoutUrl: '< ?= URL_ROOT ?>/usuario/logout', 
					keepAliveButton: 'Seguir conectado',
					logoutButton: 'Salir',
					ignoreUserActivity: false,
				});
				< ?php else: ?>
					setInterval(() => {
						$.post('< ?= URL_ROOT ?>/usuario/renovarToken/', function(resp) {}, 'json')
					}, 240000);
				< ?php endif; ?> */
			});
		</script>
	</body>
</html>