<?php 
	include 'header.phtml';

	/*if($_SESSION['usuario']->tipo == 3) {
		header('Location: '.URL_ROOT.'/tiendita');
		exit;
	}*/

	$arrMes = array('',' de Enero de ',' de Febrero de ',' de Marzo de ',' de Abril de ',' de Mayo de ',' de Junio de ',' de Julio de ',' de Agosto de ',' de Septiembre de ',' de Octubre de ',' de Noviembre de ',' de Diciembre de ');
?>
	<div class="row page-titles">
		<div class="col-md-5 align-self-center">
			<h3 class="text-themecolor"><i class="mdi mdi-chart-bubble"></i> <strong>Existencias</strong> <small>por clave de proveedor</small> Almacen General</h3>
		</div>
		<div class="col-md-7 align-self-center">
			<div class="form-inline pull-right">
				<button class="btn btn-sm btn-secondary m-l-10" id="btnPrint"><i class="mdi mdi-printer fa-lg"></i> Imprimir</button>
			</div>
		</div>
	</div>
	<div class="container-fluid">
		<div class="row">
			<div class="col-12">
				<div class="card">
					<div class="card-body">
						<h4 class="card-title">Al <?= date('d').' de '.$arrMes[date('n')].' de '.date('Y H:i:s') ?></h4>
						<!--div class="table-responsive">
						</div-->
						<table id="tbl-items" class="table table-hover table-striped table-sm w-100 mw-100">
							<thead>
								<tr>
									<th class="text-center">Clave</th>
									<th>Proveedor</th>
									<th class="text-right">Peso total</th>
								</tr>
							</thead>
							<tbody></tbody>
						</table>
					</div>
				</div>
			</div>
		</div>
	</div>

	<?php include 'footer.phtml';?>
	<script type="text/javascript">
		$(function() {
			$apiUrl = '<?= URL_API ?>producto/';
			$('#mnu-alm').addClass('show');
			$('#mnu-rpta').addClass('active');

			getItems();
			function getItems() { 
				blockPage();
				selectedColumns = $('#columns-tbl-items').val(); cleanTable('tbl-items'); $('#tbl-items tbody').empty();
				$.get($apiUrl+'stockByClave/', function(items) { 
					$.each(items, function(index, item) { addItemRow(item); });
					createTable('tbl-items', true, selectedColumns); $.unblockUI();
				});
			}

			function addItemRow(item) {
				tr = $('<tr data-id="'+item.id_producto+'"></tr>').appendTo($('#tbl-items tbody'));
				tipo = $('#item-tipo option[value="'+item.tipo+'"]').text();

				tr.append('<td class="text-center">'+item.clave+'</td>');
				tr.append('<td>'+item.proveedor+'</td>');
				tr.append('<td class="text-right">'+parseFloat(item.exist).toFixed(3)+'</td>');
			}

			function cleanTable(tbl) {
				if($.fn.dataTable.isDataTable('#'+tbl)) {
					table = $('#'+tbl).DataTable();
					table.destroy();
				}
				$("#nodata").remove();
			}

			function createTable(tbl, paging, arrColumns=null) {
				container = $('<div class="form-inline pull-right" style="overflow: visible"></div>');
				select = $('<select class="selectpicker" multiple data-selected-text-format="static" id="columns-'+tbl+'" title="Mostrar/Ocultar columnas" data-width="fit"></select>').appendTo(container);
				select.append('<option class="form-control-sm" value="0">Clave</option>');
				select.append('<option class="form-control-sm" value="1">Proveedor</option>');
				select.append('<option class="form-control-sm" value="2">Existencias</option>');
				select.selectpicker('val', arrColumns!=null? arrColumns: ['0', '1', '2']);
				searchContainer = $('<div class="input-group"></div>').appendTo(container);
				search = $('<input type="text" id="bus" placeholder="Buscar por clave, proveedor" class="form-control">').appendTo(searchContainer);
				icon = $('<div class="input-group-append"></div>').appendTo(searchContainer);
				icon.append('<button type="button" class="btn btn-secondary btn-sm" id="btn-bus"><i class="fa fa-search"></i></button>');

				$('#'+tbl).dataTable({
					// scrollY: false,
					scrollX: false,
					paging: paging,
					pagingType: "full_numbers",
					dom: 'Rl<"#toolbar-'+tbl+'">frtip',
					"columnDefs": [
						{"orderable": true, "targets": [0], "visible": ($.inArray("0", select.val())>=0)},
						{"orderable": true, "targets": [1], "visible": ($.inArray("1", select.val())>=0)},
						{"orderable": true, "targets": [2], "visible": ($.inArray("2", select.val())>=0)},
					],
					'order': [0],
					'lengthMenu': [[20,50,100,200],[20,50,100,200]]
				});

				$('#toolbar-'+tbl).html(container);
				$('#toolbar-'+tbl+' #bus').keyup(function(e) { $("#"+tbl+"_filter label input").val($.trim($(this).val())).trigger('keyup'); });
				$("#toolbar-"+tbl+" #bus").on("search", function(evt) { $("#"+tbl+"_filter label input").val(undefined).trigger('keyup'); });
				$("#toolbar-"+tbl+" #btn-bus").click(function(evt) { evt.preventDefault(); $("#"+tbl+"_filter label input").val($.trim($('#bus').val())).trigger('keyup'); });
				select.on('changed.bs.select', function(e, index) { blockPage();
					column = $('#'+tbl).DataTable().column(index);
					column.visible(!column.visible());
					$.unblockUI();
				});

				$("#"+tbl+"_filter label").hide();
			}

			$('#btnPrint').click(function(){
				window.open('<?= URL_ROOT ?>/producto/stockByClave/print/');
			});
		});
		
	</script>