<?php 
	include 'header.phtml';

	if($_SESSION['usuario']->tipo == 3) {
		header('Location: '.URL_ROOT.'/tienda');
		exit;
	}
?>
	<div class="row page-titles">
		<div class="col-md-5 align-self-center">
			<h3 class="text-themecolor"><i class="mdi mdi-shuffle-variant"></i> <strong>Transferencias</strong> Tiendita</h3>
		</div>
		<div class="col-md-7 align-self-center">
			<div class="form-inline pull-right">
				<input type="date" class="form-control form-control-sm m-r-10" id="ini" value="<?= date('Y-m-01') ?>">
				<input type="date" class="form-control form-control-sm" id="fin" value="<?= date('Y-m-d') ?>"> 
				<button class="btn btn-sm btn-secondary m-l-10" id="btnPrint"><i class="mdi mdi-printer fa-lg"></i> Imprimir</button>
			</div>
		</div>
	</div>
	<div class="container-fluid">
		<div class="row">
			<div class="col-12">
				<div class="card">
					<div class="card-body">
						<!--div class="table-responsive">
						</div-->
						<table id="tbl-items" class="table table-hover table-striped table-sm w-100 mw-100">
							<thead>
								<tr>
									<th>Fecha</th>
									<th>Usuario</th>
									<th class="text-center">Origen</th>
									<th class="text-center">Destino</th>
									<th>Producto</th>
									<th class="text-center">Cantidad</th>
									<th class="text-center"></th>
								</tr>
							</thead>
							<tbody></tbody>
						</table>
					</div>
				</div>
			</div>
		</div>
	</div>
	<?php include 'footer.phtml';?>
	<script type="text/javascript">
		$(function() {
			$apiUrl = '<?= URL_API ?>transferencia/';
			$('#mnu-tien').addClass('show');
			$('#mnu-trans').addClass('active');

			$('#ini, #fin').change(function(){ getItems(); });

			getItems();
			function getItems() { 
				blockPage();
				selectedColumns = $('#columns-tbl-items').val(); cleanTable('tbl-items'); $('#tbl-items tbody').empty();
				$.get($apiUrl+'getByDate/'+$('#ini').val()+'/'+$('#fin').val(), function(items) { 
					$.each(items, function(index, item) { addItemRow(item); });
					createTable('tbl-items', true, selectedColumns); $.unblockUI();
				});
			}

			function addItemRow(item) {
				$('#tbl-items [data-id="'+item.id_transferencia+'"]').remove();
				tr = $('<tr data-id="'+item.id_transferencia+'"></tr>').appendTo($('#tbl-items tbody'));

				tr.append('<td class="text-left"><small class="fecha">'+item.fecha+'</small></td>');
				tr.append('<td class="text-left"><small class="usuario">'+item.usuario+'</small></td>');
				tr.append('<td class="text-center"><small class="origen">'+item.origen+'</small></td>');
				tr.append('<td class="text-center"><small class="destino">'+item.destino+'</small></td>');
				tr.append('<td class="text-left"><small class="producto">'+item.producto+'</small></td>');
				tr.append('<td class="text-center"><small class="cantidad">'+item.cantidad+'</small></td>');

				tda = $('<td class="text-center"></td>');
				<?php if(in_array(MOD_TRANSFER_TIEN_DEL, $permisos)) : ?> tda.append('<a href="#" data-popup="tooltip" title="Cancelar" class="btnDel"><i class="mdi mdi-delete fa-lg" style="color:red;"></i></a>'); <?php endif; ?>
				tr.append(tda);
			}

			<?php if(in_array(MOD_TRANSFER_TIEN_DEL, $permisos)) : ?>
			$('tbody').on('click', '.btnDel', function(event) { event.preventDefault(); 
				id = $(this).parents('tr').data('id');
				trp = $('#tbl-items tr[data-id="'+id+'"]');
				prod = trp.find('td:eq(4)').text();
				fecha = trp.find('td:eq(0)').text();
				swal({ title:"Cancelar transferencia", text:"¿Desea cancelar la transferencia de <strong>"+prod+" del "+fecha+"</strong>?", type:"warning", html:true, showCancelButton:true, cancelButtonText:"No", confirmButtonColor:"#DD6B55", confirmButtonText:"Si, cancelar", closeOnConfirm:false  }, 
					function(resp) {
						blockPage();
						if(resp) {
							$.ajax({ url:$apiUrl+'cancel/'+id, type:'PUT', dataType:'json',
								success: function(resp) {
									if(resp.response) {
										trp.remove();
										swal({ type:"success", title:"¡Listo!", text:"Se cancelo la transferencia", timer:4000 });
									} else { swal({ type:"warning", title:"Oops!", text:resp.message, timer:4000 });  }
									$.unblockUI();
								}
							});
						} else { $.unblockUI(); }
					}
				);
			});
			<?php endif; ?>

			function cleanTable(tbl) {
				if($.fn.dataTable.isDataTable('#'+tbl)) {
					table = $('#'+tbl).DataTable();
					table.destroy();
				}
				$("#nodata").remove();
			}

			function createTable(tbl, paging, arrColumns=null) {
				container = $('<div class="form-inline pull-right" style="overflow: visible"></div>');
				select = $('<select class="selectpicker" multiple data-selected-text-format="static" id="columns-'+tbl+'" title="Mostrar/Ocultar columnas" data-width="fit"></select>').appendTo(container);
				select.append('<option class="form-control-sm" value="0">Fecha</option>');
				select.append('<option class="form-control-sm" value="1">Ticket</option>');
				select.append('<option class="form-control-sm" value="2">Cajero</option>');
				select.append('<option class="form-control-sm" value="3">Productos</option>');
				select.append('<option class="form-control-sm" value="4">Peso Total</option>');
				select.append('<option class="form-control-sm" value="5">Tipo</option>');
				select.append('<option class="form-control-sm" value="6">Total</option>');
				select.selectpicker('val', arrColumns!=null? arrColumns: ['0', '1', '2', '3', '4', '5']);
				searchContainer = $('<div class="input-group"></div>').appendTo(container);
				search = $('<input type="text" id="bus" placeholder="Buscar por cliente, fecha" class="form-control">').appendTo(searchContainer);
				icon = $('<div class="input-group-append"></div>').appendTo(searchContainer);
				icon.append('<button type="button" class="btn btn-secondary btn-sm" id="btn-bus"><i class="fa fa-search"></i></button>');

				$('#'+tbl).dataTable({
					// scrollY: false,
					scrollX: false,
					paging: paging,
					pagingType: "full_numbers",
					dom: 'Rl<"#toolbar-'+tbl+'">frtip',
					"columnDefs": [
						{"orderable": true, "targets": [0], "visible": ($.inArray("0", select.val())>=0)},
						{"orderable": true, "targets": [1], "visible": ($.inArray("1", select.val())>=0)},
						{"orderable": true, "targets": [2], "visible": ($.inArray("2", select.val())>=0)},
						{"orderable": true, "targets": [3], "visible": ($.inArray("3", select.val())>=0)},
						{"orderable": true, "targets": [4], "visible": ($.inArray("4", select.val())>=0)},
						{"orderable": true, "targets": [5], "visible": ($.inArray("5", select.val())>=0)},
						{"orderable": false, "targets": [6]},
					],
					'order': [0, 'desc'],
				});

				$('#toolbar-'+tbl).html(container);
				$('#toolbar-'+tbl+' #bus').keyup(function(e) { $("#"+tbl+"_filter label input").val($.trim($(this).val())).trigger('keyup'); });
				$("#toolbar-"+tbl+" #bus").on("search", function(evt) { $("#"+tbl+"_filter label input").val(undefined).trigger('keyup'); });
				$("#toolbar-"+tbl+" #btn-bus").click(function(evt) { evt.preventDefault(); $("#"+tbl+"_filter label input").val($.trim($('#bus').val())).trigger('keyup'); });
				select.on('changed.bs.select', function(e, index) { blockPage();
					column = $('#'+tbl).DataTable().column(index);
					column.visible(!column.visible());
					$.unblockUI();
				});

				$("#"+tbl+"_filter label").hide();
			}

			$('#btnPrint').click(function(){
				window.open('<?= URL_ROOT ?>/transferencia/rptTransferencias/print/'+$('#ini').val()+'/'+$('#fin').val());
			});
		});
		
	</script>